### PR TITLE
Fix for Opsworks 11.10 branch, restarting delayed_job ourselves

### PR DESCRIPTION
**Pull request by robamaton**

### CODE REVIEW

**Comment by daniel-nelson** [comment]
Hello @joeyAghion. What is the status on this please? We just moved a production app to OpsWorks and discovered that our workers are not restarting on deploy. Thank you.

**Comment by joeyAghion** [comment]
@daniel-nelson sorry for the delay. We are on Chef 11.4 _and_ use deploy hooks so this change is unsafe. I suggest using @robamaton's fork if his changes work for you. I'm open to creating a 11.10 branch on this fork if it helps, but won't be able to maintain it since we haven't yet upgraded.

**Comment by daniel-nelson** [comment]
We only have before_restart and before_migrate deploy hooks, so I'll use @robamaton's solution. Thank you @joeyAghion.

**Comment by daniel-nelson** [comment]
@loganathan-s We've been using this without issue for some time, but just today noticed that our background jobs hadn't restarted. Perhaps something changed in OpsWorks that breaks @robamaton's fix?

**Comment by robamaton** [comment]
I'm still getting confirmation in my deploy logs like this:

INFO: execute[restart delayed_job] ran successfully

Are you getting this, but they aren't restarting? Or is it not getting called at all?

**Comment by robamaton** [comment]
@daniel-nelson @loganathan-s

**Comment by daniel-nelson** [comment]
@robamaton We are seeing `execute[restart delayed_job] ran successfully` in our logs. I don't know how to explain it then, but post-multiple-deployments, our background workers were running with an outdated version of a gem that we had updated in Gemfile.lock (a custom C gem used by the background worker). After shutting down that background worker and launching a new one, the results from the background worker started reflecting the updated gem. I should have checked more carefully to see how long monit reported the workers to be running rather than assuming they hadn't been restarted before replacing the instances.

**Comment by robamaton** [comment]
@daniel-nelson Just tested in my staging environment and things are still working for me. It's possible that AWS is now deploying updated cookbooks for Chef 11.10 and my instances don't have it yet. I tested it on an m3.medium with Ubuntu 14.04 which has been running for quite a while. I can try spinning up fresh ones which might make for a better test. I'll let you know how that turns out.

**Comment by joeyAghion** [comment]
It's been long enough that I'm comfortable adding a warning about this behavior now. Next version should include this.

**Pull request merged**
